# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew clean build
    - name: Execute Gradle test
      run: ./gradlew test
    - name: Upload test report files
      uses: actions/upload-artifact@v3
      with:
        name: test-report-files
        path: ./build/test-results/test

  upload_test_results:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: test-report-files
    - name: Print hello world
      run: echo "Hello world!"
    - uses: codecov/codecov-action@v2
      with:
        files: ./build/test-results/test
