name: Spring boot integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2
    - name: Execute Gradle build
      run: ./gradlew clean build --no-daemon
    - name: Execute Gradle test
      run: ./gradlew test --no-daemon
    - name: Upload test report files
      uses: actions/upload-artifact@v3
      with:
        name: test-report-files
        path: ./build/reports/jacoco/test/jacocoTestReport.xml

  upload_coverage_report_to_codecov:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - uses: actions/checkout@v2
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: test-report-files
        path: ./testReport/
    - uses: codecov/codecov-action@v2
      with:
        files: ./testReport/jacocoTestReport.xml
        fail_ci_if_error: true

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#       - name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
